In [3]:
import numpy as np

In [25]:
ra = np.arange(36)
ra.resize(6, 6)

In [31]:
array([0,1,2,3,4,5],
      [6,7,8,9,10,11],
      [12,13,14,15,16,17],
      [18,19,20,21,22,23],
      [24,25,26,27,28,29],
      [30,31,32,33,34,35])

TypeError: 'numpy.ndarray' object is not callable

In [26]:
ra[3,2:7]

array([20, 21, 22, 23])

In [28]:
r2 = ra
r2[3,3] = 0
r2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20,  0, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [29]:
ra

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20,  0, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [45]:
import csv
%precision 2

with open('D:\\Lusofona\\3ºAno\\SIM\\cars.csv') as csvfile:
    cars = list(csv.DictReader(csvfile, delimiter=';'))
    
cars[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [48]:
len(cars)

233

In [52]:
cars[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [56]:
acc = 0
for car in cars:
    acc += int(car["cty"])

media = acc/len(cars)
media

16.86

In [58]:
sum([int(car["cty"]) for car in cars]) / len(cars)

16.86

In [59]:
sum(list(map(lambda car : int(car["cty"]),cars)))/len(cars)

16.86

In [63]:
myset = set()
for car in cars:
    myset.add(car["cyl"])
    
myset

{'audi',
 'chevrolet',
 'dodge',
 'ford',
 'honda',
 'hyundai',
 'jeep',
 'land rover',
 'lincoln',
 'mercury',
 'nissan',
 'pontiac',
 'subaru',
 'toyota',
 'volkswagen'}

In [67]:
buff={}
for car in cars:
    if car["cyl"] in buff:
        buff[car["cyl"]] = {
        "acc": int(car["cyl"]),
        "count": 1
    }
    else : 
        buff[car["cyl"]]["acc"] += int(car["cyl"])
        buff[car["cyl"]]["count"] += 1

KeyError: '4'